import type { Theme } from './types';

export const THEMES: Theme[] = [
  {
    id: 'sky',
    name: '天空藍',
    colors: {
      background: 'bg-sky-100',
      textHeader: 'text-sky-800',
      button: 'bg-sky-600',
      buttonHover: 'hover:bg-sky-700',
      buttonActive: 'active:bg-sky-800',
      progressBar: 'bg-sky-500',
      progressBarBg: 'bg-sky-200',
      textAccent: 'text-sky-500',
      inputBorder: 'border-sky-200',
      inputFocusBorder: 'focus:border-sky-500',
      inputFocusRing: 'focus:ring-sky-300',
      themeSelectorRing: 'ring-sky-500',
    },
  },
  {
    id: 'forest',
    name: '森林綠',
    colors: {
      background: 'bg-green-100',
      textHeader: 'text-green-800',
      button: 'bg-green-600',
      buttonHover: 'hover:bg-green-700',
      buttonActive: 'active:bg-green-800',
      progressBar: 'bg-green-500',
      progressBarBg: 'bg-green-200',
      textAccent: 'text-green-500',
      inputBorder: 'border-green-200',
      inputFocusBorder: 'focus:border-green-500',
      inputFocusRing: 'focus:ring-green-300',
      themeSelectorRing: 'ring-green-500',
    },
  },
    {
    id: 'sunset',
    name: '夕陽橘',
    colors: {
      background: 'bg-orange-100',
      textHeader: 'text-orange-800',
      button: 'bg-orange-500',
      buttonHover: 'hover:bg-orange-600',
      buttonActive: 'active:bg-orange-700',
      progressBar: 'bg-orange-500',
      progressBarBg: 'bg-orange-200',
      textAccent: 'text-orange-500',
      inputBorder: 'border-orange-200',
      inputFocusBorder: 'focus:border-orange-500',
      inputFocusRing: 'focus:ring-orange-300',
      themeSelectorRing: 'ring-orange-500',
    },
  },
  {
    id: 'royal',
    name: '皇家紫',
    colors: {
      background: 'bg-purple-100',
      textHeader: 'text-purple-800',
      button: 'bg-purple-600',
      buttonHover: 'hover:bg-purple-700',
      buttonActive: 'active:bg-purple-800',
      progressBar: 'bg-purple-500',
      progressBarBg: 'bg-purple-200',
      textAccent: 'text-purple-500',
      inputBorder: 'border-purple-200',
      inputFocusBorder: 'focus:border-purple-500',
      inputFocusRing: 'focus:ring-purple-300',
      themeSelectorRing: 'ring-purple-500',
    },
  },
];
